const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  const chapterLeaders = [
    {
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@example.com',
      phone: '123-456-7890',
      city: 'San Francisco',
      state: 'CA',
      reservedCity: 'San Francisco',
      address1: '123 Main St',
      address2: 'Suite 101',
      zip: '94105',
      referredByFirstName: 'Michael',
      referredByLastName: 'Jordan',
    },
    {
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane.smith@example.com',
      phone: '987-654-3210',
      city: 'Los Angeles',
      state: 'CA',
      reservedCity: 'Los Angeles',
      address1: '456 Maple Ave',
      zip: '90001',
    },
    {
      firstName: 'Alice',
      lastName: 'Johnson',
      email: 'alice.johnson@example.com',
      phone: '555-555-5555',
      city: 'New York',
      state: 'NY',
      reservedCity: 'New York',
      address1: '789 Broadway St',
      zip: '10001',
      referredByFirstName: 'Sarah',
      referredByLastName: 'Connor',
    },
    {
      firstName: 'Bob',
      lastName: 'Williams',
      email: 'bob.williams@example.com',
      phone: '666-666-6666',
      city: 'Chicago',
      state: 'IL',
      reservedCity: 'Chicago',
      address1: '101 Michigan Ave',
      zip: '60601',
    },
    {
      firstName: 'Charlie',
      lastName: 'Brown',
      email: 'charlie.brown@example.com',
      phone: '777-777-7777',
      city: 'Houston',
      state: 'TX',
      reservedCity: 'Houston',
      address1: '202 Bay Area Blvd',
      address2: 'Apt 303',
      zip: '77058',
    },
    {
      firstName: 'David',
      lastName: 'Taylor',
      email: 'david.taylor@example.com',
      phone: '888-888-8888',
      city: 'Miami',
      state: 'FL',
      reservedCity: 'Miami',
      address1: '303 Ocean Drive',
      zip: '33139',
      referredByFirstName: 'John',
      referredByLastName: 'Wick',
    },
    {
      firstName: 'Ella',
      lastName: 'Thomas',
      email: 'ella.thomas@example.com',
      phone: '999-999-9999',
      city: 'Seattle',
      state: 'WA',
      reservedCity: 'Seattle',
      address1: '404 Pine St',
      zip: '98101',
    },
    {
      firstName: 'George',
      lastName: 'Wilson',
      email: 'george.wilson@example.com',
      phone: '444-444-4444',
      city: 'Dallas',
      state: 'TX',
      reservedCity: 'Dallas',
      address1: '505 Elm St',
      zip: '75201',
      referredByFirstName: 'Jerry',
      referredByLastName: 'Seinfeld',
    },
    {
      firstName: 'Hannah',
      lastName: 'Martinez',
      email: 'hannah.martinez@example.com',
      phone: '333-333-3333',
      city: 'Phoenix',
      state: 'AZ',
      reservedCity: 'Phoenix',
      address1: '606 Grand Ave',
      zip: '85001',
      address2: 'Unit 7B',
    },
    {
      firstName: 'Ivy',
      lastName: 'Garcia',
      email: 'ivy.garcia@example.com',
      phone: '222-222-2222',
      city: 'Denver',
      state: 'CO',
      reservedCity: 'Denver',
      address1: '707 Park Ave',
      zip: '80203',
    },
    {
      firstName: 'Jack',
      lastName: 'Anderson',
      email: 'jack.anderson@example.com',
      phone: '111-111-1111',
      city: 'Boston',
      state: 'MA',
      reservedCity: 'Boston',
      address1: '808 Beacon St',
      zip: '02215',
    },
    {
      firstName: 'Karen',
      lastName: 'Moore',
      email: 'karen.moore@example.com',
      phone: '000-000-0000',
      city: 'Philadelphia',
      state: 'PA',
      reservedCity: 'Philadelphia',
      address1: '909 Walnut St',
      zip: '19106',
      referredByFirstName: 'David',
      referredByLastName: 'Beckham',
    },
    {
      firstName: 'Leo',
      lastName: 'Lee',
      email: 'leo.lee@example.com',
      phone: '999-888-7777',
      city: 'San Diego',
      state: 'CA',
      reservedCity: 'San Diego',
      address1: '1010 Balboa Ave',
      zip: '92101',
    },
    {
      firstName: 'Mia',
      lastName: 'Clark',
      email: 'mia.clark@example.com',
      phone: '123-123-1234',
      city: 'San Jose',
      state: 'CA',
      reservedCity: 'San Jose',
      address1: '1111 Silicon Valley Blvd',
      zip: '95123',
    },
    {
      firstName: 'Nathan',
      lastName: 'Lewis',
      email: 'nathan.lewis@example.com',
      phone: '555-444-3333',
      city: 'Austin',
      state: 'TX',
      reservedCity: 'Austin',
      address1: '1212 Congress Ave',
      zip: '78701',
    },
    {
      firstName: 'Olivia',
      lastName: 'Walker',
      email: 'olivia.walker@example.com',
      phone: '321-321-4321',
      city: 'Fort Worth',
      state: 'TX',
      reservedCity: 'Fort Worth',
      address1: '1313 Sundance Square',
      zip: '76102',
      referredByFirstName: 'Tom',
      referredByLastName: 'Hanks',
    },
    {
      firstName: 'Paul',
      lastName: 'Hall',
      email: 'paul.hall@example.com',
      phone: '654-654-7654',
      city: 'Columbus',
      state: 'OH',
      reservedCity: 'Columbus',
      address1: '1414 Nationwide Blvd',
      zip: '43215',
    },
    {
      firstName: 'Quinn',
      lastName: 'Young',
      email: 'quinn.young@example.com',
      phone: '789-789-8765',
      city: 'San Antonio',
      state: 'TX',
      reservedCity: 'San Antonio',
      address1: '1515 River Walk',
      zip: '78205',
    },
    {
      firstName: 'Ruby',
      lastName: 'King',
      email: 'ruby.king@example.com',
      phone: '987-987-6543',
      city: 'Charlotte',
      state: 'NC',
      reservedCity: 'Charlotte',
      address1: '1616 Uptown St',
      zip: '28202',
    },
    {
      firstName: 'Steve',
      lastName: 'Scott',
      email: 'steve.scott@example.com',
      phone: '333-222-1111',
      city: 'Detroit',
      state: 'MI',
      reservedCity: 'Detroit',
      address1: '1717 Motor City Blvd',
      zip: '48201',
    },
    // Add more records to total 50
    {
      firstName: 'Liam',
      lastName: 'Nelson',
      email: 'liam.nelson@example.com',
      phone: '123-456-7890',
      city: 'Orlando',
      state: 'FL',
      reservedCity: 'Orlando',
      address1: '1818 Orange Ave',
      zip: '32801',
    },
    {
      firstName: 'Sophia',
      lastName: 'Martinez',
      email: 'sophia.martinez@example.com',
      phone: '987-654-3210',
      city: 'Las Vegas',
      state: 'NV',
      reservedCity: 'Las Vegas',
      address1: '1919 Strip Ave',
      zip: '89109',
      referredByFirstName: 'Chris',
      referredByLastName: 'Hemsworth',
    },
    {
      firstName: 'Noah',
      lastName: 'Davis',
      email: 'noah.davis@example.com',
      phone: '555-555-5555',
      city: 'Atlanta',
      state: 'GA',
      reservedCity: 'Atlanta',
      address1: '2020 Peach St',
      zip: '30301',
    },
    {
      firstName: 'Amelia',
      lastName: 'Moore',
      email: 'amelia.moore@example.com',
      phone: '666-666-6666',
      city: 'Nashville',
      state: 'TN',
      reservedCity: 'Nashville',
      address1: '2121 Music City Blvd',
      zip: '37201',
    },
    {
      firstName: 'William',
      lastName: 'Wilson',
      email: 'william.wilson@example.com',
      phone: '777-777-7777',
      city: 'Portland',
      state: 'OR',
      reservedCity: 'Portland',
      address1: '2222 Rose City Ave',
      zip: '97201',
    },
    {
      firstName: 'Emma',
      lastName: 'White',
      email: 'emma.white@example.com',
      phone: '888-888-8888',
      city: 'Kansas City',
      state: 'MO',
      reservedCity: 'Kansas City',
      address1: '2323 Plaza Blvd',
      zip: '64101',
    },
    {
      firstName: 'James',
      lastName: 'Miller',
      email: 'james.miller@example.com',
      phone: '999-999-9999',
      city: 'Salt Lake City',
      state: 'UT',
      reservedCity: 'Salt Lake City',
      address1: '2424 Temple St',
      zip: '84101',
      referredByFirstName: 'Angelina',
      referredByLastName: 'Jolie',
    },
    {
      firstName: 'Lucas',
      lastName: 'Taylor',
      email: 'lucas.taylor@example.com',
      phone: '444-444-4444',
      city: 'Tucson',
      state: 'AZ',
      reservedCity: 'Tucson',
      address1: '2525 Desert St',
      zip: '85701',
    },
    {
      firstName: 'Evelyn',
      lastName: 'Brown',
      email: 'evelyn.brown@example.com',
      phone: '333-333-3333',
      city: 'New Orleans',
      state: 'LA',
      reservedCity: 'New Orleans',
      address1: '2626 Bourbon St',
      zip: '70116',
    },
    {
      firstName: 'Mason',
      lastName: 'Clark',
      email: 'mason.clark@example.com',
      phone: '222-222-2222',
      city: 'Minneapolis',
      state: 'MN',
      reservedCity: 'Minneapolis',
      address1: '2727 Twin City Ave',
      zip: '55401',
    },
    {
      firstName: 'Isabella',
      lastName: 'Harris',
      email: 'isabella.harris@example.com',
      phone: '111-111-1111',
      city: 'Baltimore',
      state: 'MD',
      reservedCity: 'Baltimore',
      address1: '2828 Harbor St',
      zip: '21201',
      referredByFirstName: 'Bruce',
      referredByLastName: 'Wayne',
    },
    {
      firstName: 'Oliver',
      lastName: 'Martin',
      email: 'oliver.martin@example.com',
      phone: '000-000-0000',
      city: 'Memphis',
      state: 'TN',
      reservedCity: 'Memphis',
      address1: '2929 Graceland St',
      zip: '38101',
    },
    {
      firstName: 'Charlotte',
      lastName: 'Thompson',
      email: 'charlotte.thompson@example.com',
      phone: '999-888-7777',
      city: 'Louisville',
      state: 'KY',
      reservedCity: 'Louisville',
      address1: '3030 Derby Ave',
      zip: '40202',
    },
  ];

  await prisma.chapterLeader.createMany({
    data: chapterLeaders,
  });

  console.log('Inserted 50 chapter leaders');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
